services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - $HOME/data/vol_mariadb:/var/www/wordpress:rw
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NGINX_VOLUME_LOCATION=${NGINX_VOLUME_LOCATION}
    ports:
      - '443:443'
    networks:
      - default
      - intern

  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - $HOME/data/mariadb:/var/lib/mysql:rw
    env_file:
      - .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #   - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    expose:
      - 3306
    networks:
      - default
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=localhost"]
      start_period: 1m
      interval: 5s
      timeout: 2s
      retries: 21
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/mariadb
      o: bind

networks:
    default:
      name: inception
      driver: bridge
    intern:
        internal: true
