services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress:rw
      - portfolio:/var/www/portfolio:rw
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - '443:443'
    networks:
      - default
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_started
      info:
        condition: service_started
      portfolio:
        condition: service_started
      grafana:
        condition: service_started
    restart: always

  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    expose:
      - 3306
    networks:
      - default
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=localhost"]
      start_period: 1m
      interval: 5s
      timeout: 2s
      retries: 21
    restart: always

  wordpress:
    image: inception:wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress:rw
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_PASSWORD=${WORDPRESS_USER_PASSWORD}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    expose:
      - 9000
    networks:
      - default
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-connect", "localhost:9000", "/status"]
      start_period: 1m
      interval: 5s
      timeout: 2s
      retries: 21
    restart: always

  redis:
    image: inception:redis
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    expose:
      - '6379'
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 1m
      interval: 5s
      timeout: 2s
      retries: 21
    networks:
      - default

  adminer:
    image: inception:adminer
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    expose:
      - '7077'
    networks:
      - default
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  grafana:
    image: inception:grafana
    container_name: grafana
    build:
      context: ./requirements/bonus/grafana
      dockerfile: Dockerfile
      args:
      - GRAFANA_USER=${GRAFANA_USER}
    expose:
      - '3000'
    networks:
      - default
    depends_on:
      prometheus:
        condition: service_started
    environment:
      - GRAFANA_USER=${GRAFANA_USER}
      - PROMETHEUS_HOST=${PROMETHEUS_HOST}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - grafana:/etc/grafana/provisioning:rw
    restart: always

  cadvisor:
    image: inception:cadvisor
    container_name: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    expose:
      - '8080'
    networks:
      - default
    depends_on:
      prometheus:
        condition: service_started
    environment:
      - PROMETHEUS_HOST=${PROMETHEUS_HOST}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      start_period: 1m
      interval: 30s
      timeout: 3s
      retries: 21
    restart: always

  prometheus:
    image: inception:prometheus
    container_name: prometheus
    build:
      context: ./requirements/bonus/prometheus
      dockerfile: Dockerfile
    volumes:
      - prometheus:/var/lib/prometheus:rw
    expose:
      - "9090"
    networks:
      - default
    restart: always

  ftp:
    image: inception:ftp
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - wordpress:/home/${FTP_USER}/wordpress:rw
      - portfolio:/home/${FTP_USER}/portfolio:rw
      - info:/home/${FTP_USER}/info:rw
      - grafana:/home/${FTP_USER}/grafana:rw
    depends_on:
      wordpress:
        condition: service_healthy
      portfolio:
        condition: service_started
      info:
        condition: service_started
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - default
    restart: always

  info:
    image: inception:info
    container_name: info
    build:
      context: ./requirements/bonus/info
      dockerfile: Dockerfile
    environment:
      - PROXY_URL=${PROXY_URL}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - INFO_PASSWORD=${INFO_PASSWORD}
    networks:
      - default
    volumes:
      - info:/usr/src/app/info/:rw
    restart: always

  portfolio:
    image: inception:porfolio
    container_name: portfolio
    build:
      context: ./requirements/bonus/portfolio
      dockerfile: Dockerfile
    networks:
      - default
    volumes:
      - portfolio:/var/www/portfolio:rw
    restart: always

networks:
    default:
      name: inception
      driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/wordpress
      o: bind

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/mariadb
      o: bind

  portfolio:
    name: portfolio
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/portfolio
      o: bind

  info:
    name: info
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/info
      o: bind

  grafana:
    name: grafana
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/grafana
      o: bind

  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/prometheus
      o: bind
