services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - $HOME/data/wordpress:/var/www/wordpress:rw
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NGINX_VOLUME_LOCATION=${NGINX_VOLUME_LOCATION}
    ports:
      - '443:443'
    networks:
      - default
      - intern
  # web:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./requirements/nginx/conf/thzeribi.42.fr:/etc/nginx/sites-enabled/thzeribi.42.fr:ro
  #     - ./requirements/nginx/www/:/var/www/:rw

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/wordpress
      o: bind

networks:
    default:
      name: inception
      driver: bridge
    intern:
        internal: true
