global:
  scrape_interval:     10s
  evaluation_interval: 10s
rule_files:
  - 'alert.rules'

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080